laravel/app/routes.php
<?php

// Home

Route::get('/', array(
    'as'   => 'home',
    'uses' => 'HomeController@index'
));

Route::get('home', array(
    'as'   => 'home',
    'uses' => 'HomeController@index'
));


// Reforma & Construção

Route::get('reforma-construcao', array(
    'as'   => 'reforma',
    'uses' => 'ReformaController@index'
));

Route::get('reforma-construcao/{slug_categoria}', array(
    'as'   => 'reforma.categoria',
    'uses' => 'ReformaController@categoria'
));

Route::get('reforma-construcao/{slug_categoria}/{slug_subcategoria}', array(
    'as'   => 'reforma.subcategoria',
    'uses' => 'ReformaController@subcategoria'
));


// Decoração

Route::get('decoracao', array(
    'as'   => 'decoracao',
    'uses' => 'DecoracaoController@index'
));

Route::get('decoracao/{cat}', array(
    'as'   => 'decoracao.categoria',
    'uses' => 'DecoracaoController@categoria'
));

Route::get('decoracao/{cat}/{sub}', array(
    'as'   => 'decoracao.subcategoria',
    'uses' => 'DecoracaoController@subcategoria'
));


// Marcenaria

Route::get('marcenaria', array(
    'as'   => 'marcenaria',
    'uses' => 'MarcenariaController@index'
));

Route::get('marcenaria/{slug_categoria}', array(
    'as'   => 'marcenaria.categoria',
    'uses' => 'MarcenariaController@categoria'
));


// Fotos

Route::get('fotos', array(
    'as'   => 'fotos',
    'uses' => 'FotosController@index'
));


// Depoimentos

Route::get('depoimentos', array(
    'as'   => 'depoimentos',
    'uses' => 'DepoimentosController@index'
));


// Contato

Route::get('contato', array(
    'as'   => 'contato',
    'uses' => 'ContatoController@index'
));

Route::post('envioContato', array(
    'as'   => 'contato.envio',
    'uses' => 'ContatoController@envio'
));


// Painel --------------------------------------------------------------------

Route::get('painel', array(
    'before' => 'auth',
    'as'     => 'painel.home',
    'uses'   => 'Painel\HomeController@index'
));

Route::get('painel/login', array(
    'as'   => 'painel.login',
    'uses' => 'Painel\HomeController@login'
));

Route::post('painel/login',  array('as' => 'painel.auth', function() {
    $authvars = array(
        'username' => Input::get('username'),
        'password' => Input::get('password')
    );

    $lembrar = false;

    if (Auth::attempt($authvars, $lembrar)) {
        return Redirect::to('painel');
    } else {
        Session::flash('login_errors', true);
        return Redirect::to('painel/login');
    }
}));

Route::get('painel/logout', array('as' => 'painel.off', function() {
    Auth::logout();
    return Redirect::to('painel');
}));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function() {
    Route::resource('chamadas', 'Painel\ChamadasController');
    Route::resource('slides', 'Painel\SlidesController');

    Route::resource('reforma', 'Painel\ReformaController');
    Route::resource('reformaCategorias', 'Painel\ReformaCategoriasController');
    Route::resource('reformaImagens', 'Painel\ReformaImagensController');

    Route::resource('decoracao', 'Painel\DecoracaoController');
    Route::resource('decoracaoCategorias', 'Painel\DecoracaoCategoriasController');
    Route::resource('decoracaoImagens', 'Painel\DecoracaoImagensController');

    Route::resource('marcenaria', 'Painel\MarcenariaController');
    Route::resource('marcenariaCategorias', 'Painel\MarcenariaCategoriasController');
    Route::resource('marcenariaImagens', 'Painel\MarcenariaImagensController');

    Route::resource('fotos', 'Painel\FotosController');

    Route::resource('depoimentos', 'Painel\DepoimentosController');
    Route::resource('depoimentosImagens', 'Painel\DepoimentosImagensController');

    Route::resource('contato', 'Painel\ContatoController');
    Route::resource('contatosRecebidos', 'Painel\ContatosRecebidosController');

    Route::resource('usuarios', 'Painel\UsuariosController');

    Route::post('ajax/gravaOrdem', 'Painel\AjaxController@gravaOrdem');
});

laravel/app/models/ReformaCategoria.php
<?php

class ReformaCategoria extends Eloquent
{

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'reforma_categorias';

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = array();

    // array of attributes we CAN set on the backend
    protected $fillable = array('', 'created_at', 'updated_at');

    // and those we CAN'T set on the backend
    protected $guarded = array('id');

    public function scopeSlug($query, $slug)
    {
        return $query->where('slug', '=', $slug);
    }

    public function scopeReforma_Id($query, $id)
    {
        return $query->where('reforma_id', '=', $id);
    }

    public function imagens()
    {
        return $this->hasMany('ReformaImagem', 'reforma_categoria_id');
    }

}

laravel/app/controllers/painel/ReformaCategoriasController.php
<?php

namespace Painel;

use \Reforma, \ReformaCategoria, \View, \Input, \Session, \Redirect, \Image, \Validator, \Str;

class ReformaCategoriasController extends BaseAdminController {

    public function index()
    {
        $reforma_id = Input::get('reforma_id');

        $this->layout->content = View::make('backend.reformacategorias.index')
            ->with('subcategorias', ReformaCategoria::where('reforma_id', '=', $reforma_id)->get())
            ->with('categoria', Reforma::find($reforma_id))
            ->with('reforma_id', $reforma_id);
    }

    public function create()
    {
        $reforma_id = Input::get('reforma_id');

        if(!$reforma_id)
            return Redirect::back();

        $this->layout->content = View::make('backend.reformacategorias.form')
            ->with('reforma_id', $reforma_id)
            ->with('categoria', Reforma::find($reforma_id));
    }

    public function store() {
        $reforma_id = Input::get('reforma_id');

        $object = new ReformaCategoria;

        $object->titulo = Input::get('titulo');
        $object->descricao = Input::get('descricao');
        $object->slug = Str::slug(Input::get('titulo'));
        $object->reforma_id = $reforma_id;

        $imagem = Input::file('imagem_capa');

        $rules = array('imagem_capa' => 'image');
        $validation = Validator::make(array('imagem_capa' => $imagem), $rules);

        if (ReformaCategoria::where('reforma_id', '=', $reforma_id)->where('slug', '=', $object->slug)->count() > 0) {

            Session::flash('formulario', Input::except('imagem_capa'));
            return Redirect::back()->withErrors(array('Erro: Já existe outra subcategoria com o mesmo título'));

        }

        if ($validation->fails()) {

            Session::flash('formulario', Input::except('imagem_capa'));
            return Redirect::back()->withErrors(array('Erro: O arquivo deve ser uma imagem!'));

        } else {

            $name = date('YmdHis').$imagem->getClientOriginalName();
            $path = 'assets/img/reforma/capa/'.$name;

            $imgobj = Image::make(Input::file('imagem_capa')->getRealPath());
            $imgobj->fit(420, 120, function ($constraint) {
                $constraint->upsize();
            })->save($path, 100);

            $object->imagem_capa = $name;

        }

        try {

            $object->save();
            Session::flash('sucesso', true);
            Session::flash('mensagem', 'Subcategoria criada com sucesso.');
            return Redirect::route('painel.reformacategorias.index', array('reforma_id' => $reforma_id));

        } catch (\Exception $e) {

            Session::flash('formulario', Input::except('imagem_capa'));
            return Redirect::back()->withErrors(array('Erro ao criar subcategoria! Verifique se já existe outra subcategoria com o mesmo título'));

        }
    }

    public function show() {}

    public function edit($id)
    {
        $reforma_id = Input::get('reforma_id');

        $this->layout->content = View::make('backend.reformacategorias.edit')
            ->with('subcategoria', ReformaCategoria::find($id))
            ->with('reforma_id', $reforma_id);
    }

    public function update($id)
    {
        $reforma_id = Input::get('reforma_id');

        $object = ReformaCategoria::find($id);

        $object->titulo = Input::get('titulo');
        $object->descricao = Input::get('descricao');
        $object->slug = Str::slug(Input::get('titulo'));

        if (ReformaCategoria::where('reforma_id', '=', $reforma_id)->where('slug', '=', $object->slug)->count() > 0) {

            Session::flash('formulario', Input::except('imagem_capa'));
            return Redirect::back()->withErrors(array('Erro: Já existe outra subcategoria com o mesmo título'));

        }

        if (Input::hasFile('imagem_capa')) {

            $imagem = Input::file('imagem_capa');

            $rules = array('imagem_capa' => 'image');
            $validation = Validator::make(array('imagem_capa' => $imagem), $rules);

            if ($validation->fails()) {

                Session::flash('formulario', Input::except('imagem_capa'));
                return Redirect::back()->withErrors(array('Erro: O arquivo deve ser uma imagem!'));

            } else {

                $name = date('YmdHis').$imagem->getClientOriginalName();
                $path = 'assets/img/reforma/capa/'.$name;

                $imgobj = Image::make(Input::file('imagem_capa')->getRealPath());
                $imgobj->fit(420, 120, function ($constraint) {
                    $constraint->upsize();
                })->save($path, 100);

                $object->imagem_capa = $name;

            }

        }

        try {

            $object->save();
            Session::flash('sucesso', true);
            Session::flash('mensagem', 'Subcategoria editada com sucesso.');
            return Redirect::route('painel.reformacategorias.index', array('reforma_id' => $reforma_id));

        } catch (\Exception $e) {

            Session::flash('formulario', Input::except('imagem_capa'));
            return Redirect::back()->withErrors(array('Erro ao editar subcategoria! Verifique se já existe outra subcategoria com o mesmo título'));

        }
    }

    public function destroy($id)
    {
        $reforma_id = Input::get('reforma_id');

        $object = ReformaCategoria::find($id);
        $object->delete();

        Session::flash('sucesso', true);
        Session::flash('mensagem', 'Subcategoria removida com sucesso.');

        return Redirect::route('painel.reformacategorias.index', array('reforma_id' => $reforma_id));
    }

}

laravel/app/views/backend/reformaCategorias/edit.blade.php
@section('content')

    <legend>
        <h2><small>{{$subcategoria->titulo}} /</small> Editar Subcategoria</h2>
    </legend>

    {{ Form::open( array('route' => array('painel.reformaCategorias.update', $subcategoria->id), 'files' => true, 'method' => 'put') ) }}
        <div class="pad">

            @if(Session::has('sucesso'))
               <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
            @endif

            @if($errors->any())
                <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
            @endif

            <div class="form-group">
                <label for="inputTitulo">Título</label>
                <input type="text" class="form-control" id="inputTitulo" name="titulo" value="{{$subcategoria->titulo}}" required>
            </div>

            <div class="form-group">
                <label for="inputDesc">Descrição</label>
                <textarea name="descricao" id="inputDesc" class="form-control" rows="6" required>{{$subcategoria->descricao}}</textarea>
            </div>

            <div class="form-group">
                <label>Imagem de capa atual</label><br>
                <img src="{{url('assets/img/reforma/capa/'.$subcategoria->imagem_capa)}}" alt=""><br>
                <label for="inputImagem">Trocar Imagem <small>(420x120 px)</small></label>
                <input type="file" class="form-control" id="inputImagem" name="imagem_capa">
            </div>

            <input type="hidden" name="reforma_id" value="{{$reforma_id}}">

            <button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

            <a href="{{URL::route('painel.reformaCategorias.index', array('reforma_id' => $reforma_id))}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

        </div>
    </form>

@stop

laravel/app/views/backend/reformaCategorias/form.blade.php
@section('content')

    <legend>
        <h2><small>{{$categoria->titulo}} /</small> Adicionar Subcategoria</h2>
    </legend>

    <form action="{{URL::route('painel.reformaCategorias.store')}}" method="post" enctype="multipart/form-data">
        <div class="pad">

            @if(Session::has('sucesso'))
               <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
            @endif

            @if($errors->any())
                <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
            @endif

            <div class="form-group">
                <label for="inputTitulo">Título</label>
                <input type="text" class="form-control" id="inputTitulo" name="titulo"  @if(Session::has('formulario')) value="{{ Session::get('formulario.titulo') }}" @endif required>
            </div>

            <div class="form-group">
                <label for="inputDesc">Descrição</label>
                <textarea name="descricao" id="inputDesc" class="form-control" rows="6" required>@if(Session::has('formulario')){{ Session::get('formulario.descricao') }}@endif</textarea>
            </div>

            <div class="form-group">
                <label for="inputImagem">Imagem de capa <small>(420x120 px)</small></label>
                <input type="file" class="form-control" id="inputImagem" name="imagem_capa" required>
            </div>

            <input type="hidden" name="reforma_id" value="{{$reforma_id}}">

            <button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

            <a href="{{URL::route('painel.reformaCategorias.index', array('reforma_id' => $reforma_id))}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

        </div>
    </form>

@stop

laravel/app/views/backend/reformaCategorias/index.blade.php
@section('content')

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <a href="{{URL::route('painel.reforma.index')}}" title="Voltar para Reforma e Construção" class="btn btn-default">&larr; Voltar para Reforma e Construção</a>

    <legend>
        <h2>
            <small>Reforma e Construção / </small> {{$categoria->titulo}}
            <a href="{{ URL::route('painel.reformaCategorias.create', array('reforma_id' => $reforma_id)) }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus-sign"></span> Adicionar Subcategoria</a>
        </h2>
    </legend>

    @if(sizeof($subcategorias))
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th>Capa</th>
                    <th>Título</th>
                    <th>Imagens</th>
                    <th><span class="glyphicon glyphicon-cog"></span></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($subcategorias as $subcategoria)
                <tr>
                    <td><img src="{{url('assets/img/reforma/capa/'.$subcategoria->imagem_capa)}}" alt=""></td>
                    <td>{{$subcategoria->titulo}}</td>
                    <td>
                        <a href="{{URL::route('painel.reformaImagens.index', array('reforma_categoria_id' => $subcategoria->id))}}" class="btn btn-sm btn-default">gerenciar</a>
                    </td>
                    <td class="crud-actions">
                        <a href="{{ URL::route('painel.reformaCategorias.edit', array($subcategoria->id, 'reforma_id' => $reforma_id)) }}" class="btn btn-primary btn-sm pull-left">editar</a>
                       {{ Form::open(array('route' => array('painel.reformaCategorias.destroy', $subcategoria->id), 'method' => 'delete')) }}
                            <input type="hidden" name="reforma_id" value="{{$reforma_id}}">
                            <button type="submit" class="btn btn-danger btn-sm btn-delete">excluir</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="alert alert-warning" role="alert">Nenhuma subcategoria cadastrada, utilize o menu superior para inserir subcategorias.</div>
    @endif

@stop