laravel/app/routes.php
<?php

// Home

Route::get('/', array(
    'as'   => 'home',
    'uses' => 'HomeController@index'
));

Route::get('home', array(
    'as'   => 'home',
    'uses' => 'HomeController@index'
));


// Reforma & Construção

Route::get('reforma-construcao', array(
    'as'   => 'reforma',
    'uses' => 'ReformaController@index'
));

Route::get('reforma-construcao/{slug_categoria}', array(
    'as'   => 'reforma.categoria',
    'uses' => 'ReformaController@categoria'
));

Route::get('reforma-construcao/{slug_categoria}/{slug_subcategoria}', array(
    'as'   => 'reforma.subcategoria',
    'uses' => 'ReformaController@subcategoria'
));


// Decoração

Route::get('decoracao', array(
    'as'   => 'decoracao',
    'uses' => 'DecoracaoController@index'
));

Route::get('decoracao/{cat}', array(
    'as'   => 'decoracao.categoria',
    'uses' => 'DecoracaoController@categoria'
));

Route::get('decoracao/{cat}/{sub}', array(
    'as'   => 'decoracao.subcategoria',
    'uses' => 'DecoracaoController@subcategoria'
));


// Marcenaria

Route::get('marcenaria', array(
    'as'   => 'marcenaria',
    'uses' => 'MarcenariaController@index'
));

Route::get('marcenaria/{slug_categoria}', array(
    'as'   => 'marcenaria.categoria',
    'uses' => 'MarcenariaController@categoria'
));


// Fotos

Route::get('fotos', array(
    'as'   => 'fotos',
    'uses' => 'FotosController@index'
));


// Depoimentos

Route::get('depoimentos', array(
    'as'   => 'depoimentos',
    'uses' => 'DepoimentosController@index'
));


// Contato

Route::get('contato', array(
    'as'   => 'contato',
    'uses' => 'ContatoController@index'
));

Route::post('envioContato', array(
    'as'   => 'contato.envio',
    'uses' => 'ContatoController@envio'
));


// Painel --------------------------------------------------------------------

Route::get('painel', array(
    'before' => 'auth',
    'as'     => 'painel.home',
    'uses'   => 'Painel\HomeController@index'
));

Route::get('painel/login', array(
    'as'   => 'painel.login',
    'uses' => 'Painel\HomeController@login'
));

Route::post('painel/login',  array('as' => 'painel.auth', function() {
    $authvars = array(
        'username' => Input::get('username'),
        'password' => Input::get('password')
    );

    $lembrar = false;

    if (Auth::attempt($authvars, $lembrar)) {
        return Redirect::to('painel');
    } else {
        Session::flash('login_errors', true);
        return Redirect::to('painel/login');
    }
}));

Route::get('painel/logout', array('as' => 'painel.off', function() {
    Auth::logout();
    return Redirect::to('painel');
}));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function() {
    Route::resource('chamadas', 'Painel\ChamadasController');
    Route::resource('slides', 'Painel\SlidesController');

    Route::resource('reforma', 'Painel\ReformaController');
    Route::resource('reformaCategorias', 'Painel\ReformaCategoriasController');
    Route::resource('reformaImagens', 'Painel\ReformaImagensController');

    Route::resource('decoracao', 'Painel\DecoracaoController');
    Route::resource('decoracaoCategorias', 'Painel\DecoracaoCategoriasController');
    Route::resource('decoracaoImagens', 'Painel\DecoracaoImagensController');

    Route::resource('marcenaria', 'Painel\MarcenariaController');
    Route::resource('marcenariaCategorias', 'Painel\MarcenariaCategoriasController');
    Route::resource('marcenariaImagens', 'Painel\MarcenariaImagensController');

    Route::resource('fotos', 'Painel\FotosController');

    Route::resource('depoimentos', 'Painel\DepoimentosController');
    Route::resource('depoimentosImagens', 'Painel\DepoimentosImagensController');

    Route::resource('contato', 'Painel\ContatoController');
    Route::resource('contatosRecebidos', 'Painel\ContatosRecebidosController');

    Route::resource('usuarios', 'Painel\UsuariosController');

    Route::post('ajax/gravaOrdem', 'Painel\AjaxController@gravaOrdem');
});

laravel/app/controllers/painel/MarcenariaImagensController.php
<?php

namespace Painel;

use \MarcenariaCategoria, \MarcenariaImagem, \View, \Input, \Session, \Redirect, \Validator, \Image;

class MarcenariaImagensController extends BaseAdminController {

    protected $layout = 'backend.template.index';

    public function index()
    {
        $marcenaria_categorias_id = (Input::get('marcenaria_categorias_id') ?: 0);

        $categoria = ($marcenaria_categorias_id == 0 ? 'Marcenaria' : MarcenariaCategoria::find($marcenaria_categorias_id));

        $this->layout->content = View::make('backend.marcenariaimagens.index')
            ->with('imagens', MarcenariaImagem::orderBy('id', 'desc')->where('marcenaria_categorias_id', $marcenaria_categorias_id)->get())
            ->with(compact('categoria'))
            ->with(compact('marcenaria_categorias_id'));
    }

    public function create() {
        $marcenaria_categorias_id = (Input::get('marcenaria_categorias_id') ?: 0);

        $categoria = ($marcenaria_categorias_id == 0 ? 'Marcenaria' : MarcenariaCategoria::find($marcenaria_categorias_id));

        $this->layout->content = View::make('backend.marcenariaimagens.form')
            ->with(compact('categoria'))
            ->with(compact('marcenaria_categorias_id'));
    }

    public function store() {
        $marcenaria_categorias_id = Input::get('marcenaria_categorias_id');

        $object = new MarcenariaImagem;

        $imagem = Input::file('imagem');
        $object->marcenaria_categorias_id = $marcenaria_categorias_id;

        $rules = array('imagem' => 'image');
        $validation = Validator::make(array('imagem' => $imagem), $rules);

        if ($validation->fails()) {
            return Redirect::back()->withErrors(array('Erro: O arquivo deve ser uma imagem!'));
        } else {

            $name = date('YmdHis').$imagem->getClientOriginalName();
            $path = 'assets/img/marcenaria/'.$name;
            $path_t = 'assets/img/marcenaria/thumb/'.$name;

            $imgobj = Image::make(Input::file('imagem')->getRealPath());
            $ratio = $imgobj->width() / $imgobj->height();

            // ajusta largura ou altura dependendo da proporção
            if ($ratio > 1) {
                $imgobj->widen(800, function ($constraint) {
                    $constraint->upsize();
                })->save($path, 100);
            } else {
                $imgobj->heighten(720, function ($constraint) {
                    $constraint->upsize();
                })->save($path, 100);
            }

            // gera thumb 120x116
            $imgobj->fit(120, 116, function ($constraint) {
                $constraint->upsize();
            })->save($path_t, 100);

            $object->imagem = $name;

        }

        try {

            $object->save();
            Session::flash('sucesso', true);
            Session::flash('mensagem', 'Imagem adicionada com sucesso.');
            return Redirect::route('painel.marcenariaimagens.index', array('marcenaria_categorias_id' => $marcenaria_categorias_id));

        } catch (\Exception $e) {

            Session::flash('formulario', Input::all());
            return Redirect::back()->withErrors(array('Erro ao adicionar imagem!'));

        }
    }
    public function show() {}
    public function edit($id) {}
    public function update($id) {}

    public function destroy($id) {
        $marcenaria_categorias_id = Input::get('marcenaria_categorias_id');

        $object = MarcenariaImagem::find($id);
        $object->delete();

        Session::flash('sucesso', true);
        Session::flash('mensagem', 'Imagem removida com sucesso.');

        return Redirect::route('painel.marcenariaimagens.index', array('marcenaria_categorias_id' => $marcenaria_categorias_id));
    }

}

laravel/app/views/backend/marcenariaImagens/form.blade.php
@section('content')

    <legend>
        <h2>Adicionar Imagem a: @if($categoria=='Marcenaria')Marcenaria
        @else{{$categoria->titulo}}@endif</h2>
    </legend>

    <form action="{{URL::route('painel.marcenariaImagens.store')}}" method="post" enctype="multipart/form-data">
        <div class="pad">

            @if(Session::has('sucesso'))
               <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
            @endif

            @if($errors->any())
                <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
            @endif

            <div class="form-group">
                <label for="inputImagem">Imagem</small></label>
                <input type="file" class="form-control" id="inputImagem" name="imagem" required>
            </div>

            <input type="hidden" name="marcenaria_categorias_id" value="{{$marcenaria_categorias_id}}">

            <button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

            <a href="{{URL::route('painel.marcenariaImagens.index', array('marcenaria_categorias_id' => $marcenaria_categorias_id))}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

        </div>
    </form>

@stop

laravel/app/views/backend/marcenariaImagens/index.blade.php
@section('content')

    @if(Session::has('sucesso'))
       <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <a href="{{URL::route('painel.marcenaria.index')}}" title="Voltar para Marcenaria" class="btn btn-default">&larr; Voltar para Marcenaria</a>

    <h2>
        Imagens de: @if($categoria=='Marcenaria')Marcenaria
        @else{{$categoria->titulo}}@endif
        <a href="{{ URL::route('painel.marcenariaImagens.create', array('marcenaria_categorias_id' => $marcenaria_categorias_id)) }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus-sign"></span>  Adicionar Foto</a>
    </h2>

    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>Imagem</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
            @foreach ($imagens as $imagem)

                <tr class="tr-row">
                    <td><img src="{{url('assets/img/marcenaria/thumb/'.$imagem->imagem)}}"></td>
                    <td class="crud-actions">
                       {{ Form::open(array('route' => array('painel.marcenariaImagens.destroy', $imagem->id), 'method' => 'delete')) }}
                        <input type="hidden" name="marcenaria_categorias_id" value="{{$marcenaria_categorias_id}}">
                            <button type="submit" class="btn btn-danger btn-sm btn-delete">excluir</button>
                       {{ Form::close() }}
                    </td>
                </tr>

            @endforeach
        </tbody>
    </table>

</div>

@stop