laravel/app/routes.php
<?php

// Home

Route::get('/', array(
    'as'   => 'home',
    'uses' => 'HomeController@index'
));

Route::get('home', array(
    'as'   => 'home',
    'uses' => 'HomeController@index'
));


// Reforma & Construção

Route::get('reforma-construcao', array(
    'as'   => 'reforma',
    'uses' => 'ReformaController@index'
));

Route::get('reforma-construcao/{slug_categoria}', array(
    'as'   => 'reforma.categoria',
    'uses' => 'ReformaController@categoria'
));

Route::get('reforma-construcao/{slug_categoria}/{slug_subcategoria}', array(
    'as'   => 'reforma.subcategoria',
    'uses' => 'ReformaController@subcategoria'
));


// Decoração

Route::get('decoracao', array(
    'as'   => 'decoracao',
    'uses' => 'DecoracaoController@index'
));

Route::get('decoracao/{cat}', array(
    'as'   => 'decoracao.categoria',
    'uses' => 'DecoracaoController@categoria'
));

Route::get('decoracao/{cat}/{sub}', array(
    'as'   => 'decoracao.subcategoria',
    'uses' => 'DecoracaoController@subcategoria'
));


// Marcenaria

Route::get('marcenaria', array(
    'as'   => 'marcenaria',
    'uses' => 'MarcenariaController@index'
));

Route::get('marcenaria/{slug_categoria}', array(
    'as'   => 'marcenaria.categoria',
    'uses' => 'MarcenariaController@categoria'
));


// Fotos

Route::get('fotos', array(
    'as'   => 'fotos',
    'uses' => 'FotosController@index'
));


// Depoimentos

Route::get('depoimentos', array(
    'as'   => 'depoimentos',
    'uses' => 'DepoimentosController@index'
));


// Contato

Route::get('contato', array(
    'as'   => 'contato',
    'uses' => 'ContatoController@index'
));

Route::post('envioContato', array(
    'as'   => 'contato.envio',
    'uses' => 'ContatoController@envio'
));


// Painel --------------------------------------------------------------------

Route::get('painel', array(
    'before' => 'auth',
    'as'     => 'painel.home',
    'uses'   => 'Painel\HomeController@index'
));

Route::get('painel/login', array(
    'as'   => 'painel.login',
    'uses' => 'Painel\HomeController@login'
));

Route::post('painel/login',  array('as' => 'painel.auth', function() {
    $authvars = array(
        'username' => Input::get('username'),
        'password' => Input::get('password')
    );

    $lembrar = false;

    if (Auth::attempt($authvars, $lembrar)) {
        return Redirect::to('painel');
    } else {
        Session::flash('login_errors', true);
        return Redirect::to('painel/login');
    }
}));

Route::get('painel/logout', array('as' => 'painel.off', function() {
    Auth::logout();
    return Redirect::to('painel');
}));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function() {
    Route::resource('chamadas', 'Painel\ChamadasController');
    Route::resource('slides', 'Painel\SlidesController');

    Route::resource('reforma', 'Painel\ReformaController');
    Route::resource('reformaCategorias', 'Painel\ReformaCategoriasController');
    Route::resource('reformaImagens', 'Painel\ReformaImagensController');

    Route::resource('decoracao', 'Painel\DecoracaoController');
    Route::resource('decoracaoCategorias', 'Painel\DecoracaoCategoriasController');
    Route::resource('decoracaoImagens', 'Painel\DecoracaoImagensController');

    Route::resource('marcenaria', 'Painel\MarcenariaController');
    Route::resource('marcenariaCategorias', 'Painel\MarcenariaCategoriasController');
    Route::resource('marcenariaImagens', 'Painel\MarcenariaImagensController');

    Route::resource('fotos', 'Painel\FotosController');

    Route::resource('depoimentos', 'Painel\DepoimentosController');
    Route::resource('depoimentosImagens', 'Painel\DepoimentosImagensController');

    Route::resource('contato', 'Painel\ContatoController');
    Route::resource('contatosRecebidos', 'Painel\ContatosRecebidosController');

    Route::resource('usuarios', 'Painel\UsuariosController');

    Route::post('ajax/gravaOrdem', 'Painel\AjaxController@gravaOrdem');
});

laravel/app/models/Reforma.php
<?php

class Reforma extends Eloquent
{

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'reforma';

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = array();

    // array of attributes we CAN set on the backend
    protected $fillable = array('', 'created_at', 'updated_at');

    // and those we CAN'T set on the backend
    protected $guarded = array('id');

    public function scopeSlug($query, $slug)
    {
        return $query->where('slug', '=', $slug);
    }

    public function imagens()
    {
        return $this->hasMany('ReformaImagem', 'reforma_id');
    }

}

laravel/app/controllers/ReformaController.php
<?php

use \ReformaCategoria, \ReformaImagem;

class ReformaController extends BaseController {

	protected $layout = 'frontend.template.index';

	public function index()
	{

        $reformas = Reforma::get();

		$this->layout->content = View::make('frontend.reforma.index')
            ->with(compact('reformas'));

	}

    public function categoria($slug_categoria)
    {

        $reformas  = Reforma::get();

        $categoria = Reforma::slug($slug_categoria)->first();
        if(!$categoria) App::abort('404');

        $subcategorias = ReformaCategoria::reforma_id($categoria->id)->get();

        $imagens = Reforma::find($categoria->id)->imagens;

        $this->layout->content = View::make('frontend.reforma.categoria')
            ->with(compact('reformas'))
            ->with(compact('categoria'))
            ->with(compact('subcategorias'))
            ->with(compact('imagens'));

    }

    public function subcategoria($slug_categoria, $slug_subcategoria)
    {

        $reformas  = Reforma::get();

        $categoria = Reforma::slug($slug_categoria)->first();
        if(!$categoria) App::abort('404');

        $subcategoria = ReformaCategoria::slug($slug_subcategoria)->first();
        if(!$subcategoria) App::abort('404');

        $imagens = ReformaCategoria::find($subcategoria->id)->imagens()->orderBy('id', 'desc')->get();

        $this->layout->content = View::make('frontend.reforma.subcategoria')
            ->with(compact('reformas'))
            ->with(compact('categoria'))
            ->with(compact('subcategoria'))
            ->with(compact('imagens'));

    }

}

laravel/app/controllers/painel/ReformaController.php
<?php

namespace Painel;

use \Reforma, \View, \Input, \Session, \Redirect, \Image, \Validator, \Str;

class ReformaController extends BaseAdminController {

    public function index()
    {
        $this->layout->content = View::make('backend.reforma.index')
            ->with('categorias', Reforma::get());
    }

    public function create()
    {
        $this->layout->content = View::make('backend.reforma.form');
    }

    public function store()
    {
        $object = new Reforma;

        $object->titulo = Input::get('titulo');
        $object->olho = Input::get('olho');
        $object->descricao = Input::get('descricao');
        $object->slug = Str::slug(Input::get('titulo'));

        $imagem = Input::file('thumb');

        $rules = array('thumb' => 'image');
        $validation = Validator::make(array('thumb' => $imagem), $rules);

        if ($validation->fails()) {

            Session::flash('formulario', Input::except('thumb'));
            return Redirect::back()->withErrors(array('Erro: O arquivo deve ser uma imagem!'));

        } else {

            $name = date('YmdHis').$imagem->getClientOriginalName();
            $path = 'assets/img/reforma/thumb_home/'.$name;
            Image::make(Input::file('thumb')->getRealPath())->save($path, 100);
            $object->thumb = $name;

        }

        try {

            $object->save();
            Session::flash('sucesso', true);
            Session::flash('mensagem', 'Categoria criada com sucesso.');
            return Redirect::route('painel.reforma.index');

        } catch (\Exception $e) {

            Session::flash('formulario', Input::except('thumb'));
            return Redirect::back()->withErrors(array('Erro ao criar categoria! Verifique se já existe outra categoria com o mesmo título'));

        }
    }

    public function show() {}

    public function edit($id)
    {
        $this->layout->content = View::make('backend.reforma.edit')
            ->with('categoria', Reforma::find($id));
    }

    public function update($id)
    {
        $object = Reforma::find($id);

        $object->titulo = Input::get('titulo');
        $object->olho = Input::get('olho');
        $object->descricao = Input::get('descricao');
        $object->slug = Str::slug(Input::get('titulo'));

        if (Input::hasFile('thumb')) {

            $imagem = Input::file('thumb');

            $rules = array('thumb' => 'image');
            $validation = Validator::make(array('thumb' => $imagem), $rules);

            if ($validation->fails()) {

                Session::flash('formulario', Input::except('thumb'));
                return Redirect::back()->withErrors(array('Erro: O arquivo deve ser uma imagem!'));

            } else {

                $name = date('YmdHis').$imagem->getClientOriginalName();
                $path = 'assets/img/reforma/thumb_home/'.$name;
                Image::make(Input::file('thumb')->getRealPath())->save($path, 100);
                $object->thumb = $name;

            }

        }

        try {

            $object->save();
            Session::flash('sucesso', true);
            Session::flash('mensagem', 'Categoria alterada com sucesso.');
            return Redirect::route('painel.reforma.index');

        } catch (\Exception $e) {

            Session::flash('formulario', Input::except('thumb'));
            return Redirect::back()->withErrors(array('Erro ao alterar categoria! Verifique se já existe outra categoria com o mesmo título'));

        }
    }

    public function destroy($id) {
        $object = Reforma::find($id);
        $object->delete();

        Session::flash('sucesso', true);
        Session::flash('mensagem', 'Categoria removida com sucesso.');

        return Redirect::route('painel.reforma.index');
    }

}

laravel/app/views/backend/reforma/edit.blade.php
@section('content')

    <legend>
        <h2><small>Reforma e Construção /</small> Editar Categoria</h2>
    </legend>

    {{ Form::open( array('route' => array('painel.reforma.update', $categoria->id), 'files' => true, 'method' => 'put') ) }}
        <div class="pad">

            @if(Session::has('sucesso'))
               <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
            @endif

            @if($errors->any())
                <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
            @endif

            <div class="form-group">
                <label for="inputTitulo">Título</label>
                <input type="text" class="form-control" id="inputTitulo" name="titulo" value="{{$categoria->titulo}}" required>
            </div>

            <div class="form-group">
                <label for="inputOlho">Olho</label>
                <input type="text" class="form-control" id="inputOlho" name="olho" value="{{$categoria->olho}}" required>
            </div>

            <div class="form-group">
                <label for="inputDesc">Descrição</label>
                <textarea name="descricao" id="inputDesc" class="form-control" rows="6" required>{{$categoria->descricao}}</textarea>
            </div>

            <div class="form-group">
                <label>Imagem de capa atual</label><br>
                <img src="{{url('assets/img/reforma/thumb_home/'.$categoria->thumb)}}" alt=""><br>
                <label for="inputImagem">Trocar Imagem <small>(214x214 px)</small></label>
                <input type="file" class="form-control" id="inputImagem" name="thumb">
            </div>

            <button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

            <a href="{{URL::route('painel.reforma.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

        </div>
    </form>

@stop

laravel/app/views/backend/reforma/form.blade.php
@section('content')

    <legend>
        <h2><small>Reforma e Construção /</small> Adicionar Categoria</h2>
    </legend>

    <form action="{{URL::route('painel.reforma.store')}}" method="post" enctype="multipart/form-data">
        <div class="pad">

            @if(Session::has('sucesso'))
               <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
            @endif

            @if($errors->any())
                <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
            @endif

            <div class="form-group">
                <label for="inputTitulo">Título</label>
                <input type="text" class="form-control" id="inputTitulo" name="titulo"  @if(Session::has('formulario')) value="{{ Session::get('formulario.titulo') }}" @endif required>
            </div>

            <div class="form-group">
                <label for="inputOlho">Olho</label>
                <textarea name="olho" id="inputOlho" class="form-control" rows="3" required>@if(Session::has('formulario')){{ Session::get('formulario.olho') }}@endif</textarea>
            </div>

            <div class="form-group">
                <label for="inputDesc">Descrição</label>
                <textarea name="descricao" id="inputDesc" class="form-control" rows="6" required>@if(Session::has('formulario')){{ Session::get('formulario.descricao') }}@endif</textarea>
            </div>

            <div class="form-group">
                <label for="inputImagem">Imagem de capa <small>(214x214 px)</small></label>
                <input type="file" class="form-control" id="inputImagem" name="thumb" required>
            </div>

            <button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

            <a href="{{URL::route('painel.reforma.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

        </div>
    </form>

@stop

laravel/app/views/backend/reforma/index.blade.php
@section('content')

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <legend>
        <h2>
            Reforma e Construção
            <a href="{{ URL::route('painel.reforma.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus-sign"></span> Adicionar Categoria</a>
        </h2>
    </legend>

    @if(sizeof($categorias))
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th>Capa</th>
                    <th>Título</th>
                    <th>Imagens</th>
                    <th>Subcategorias</th>
                    <th><span class="glyphicon glyphicon-cog"></span></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($categorias as $categoria)
                <tr>
                    <td><img src="{{url('assets/img/reforma/thumb_home/'.$categoria->thumb)}}" alt="" style="max-width: 150px;"></td>
                    <td>{{$categoria->titulo}}</td>
                    <td>
                        <a href="{{URL::route('painel.reformaImagens.index', array('reforma_id' => $categoria->id))}}" class="btn btn-sm btn-default">gerenciar</a>
                    </td>
                    <td>
                        <a href="{{URL::route('painel.reformaCategorias.index', array('reforma_id' => $categoria->id))}}" class="btn btn-sm btn-default">gerenciar</a>
                    </td>
                    <td class="crud-actions">
                        <a href="{{ URL::route('painel.reforma.edit', $categoria->id ) }}" class="btn btn-primary btn-sm pull-left">editar</a>
                       {{ Form::open(array('route' => array('painel.reforma.destroy', $categoria->id), 'method' => 'delete')) }}
                            <button type="submit" class="btn btn-danger btn-sm btn-delete">excluir</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="alert alert-warning" role="alert">Nenhuma categoria cadastrada, utilize o menu superior para inserir categorias.</div>
    @endif

@stop